[package]
name = "erased-serde"
version = "0.3.1"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Type-erased Serialize and Serializer traits"
repository = "https://github.com/dtolnay/erased-serde"
documentation = "https://github.com/dtolnay/erased-serde"
keywords = ["serde", "erasure"]
include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]
serde = "1.0"

[dev-dependencies]
serde_cbor = "0.6"
serde_derive = "1.0"
serde_json = "1.0"

[features]
unstable-debug = []

[[test]]
name = "test"
path = "tests/readme.rs"
