[package]
name = "erased-serde"
version = "0.1.3"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Type-erased Serialize and Serializer traits"
repository = "https://github.com/dtolnay/erased-serde"
documentation = "https://github.com/dtolnay/erased-serde"
keywords = ["serde", "erasure"]
include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]
serde = "0.9"

[dev-dependencies]
serde_cbor = "0.5"
serde_json = "0.9"

[[test]]
name = "test"
path = "tests/readme.rs"
